before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: EQXu5YDEQgYW4v3Ad7vSh/7//LxGZMp3UOAqsrpySJl8ikLP85r28P43BBBNuM9weJ3BRy5ABf9dy/3RYrt2Cid0vZGtJLyvfUgG1YnVWnTq/cza3+Fbni5Y7MejMN6SSN5z0uJS0v6L/COh/9e5pEUf7V4zWKY+YZvkh1ugVXFpSrdPvu6pQHZmPSpPItPSfRHTwmqHKrHfhH1CwPZ9B4ArUoZPNdDmgn/Y4lY6G0Dyt25/k1g2xiwkka165apO0On10Id27Q8jWt+R3r7ZHi0AMsPJKR/PDCD6UnnsmcnBixSVI5XWrrotjdd9g0wLQpXYxJxMfdG7hfd213craA6Qiqh4zryi8nURIIDbgZ0hEgL9KJ/JVqrd4VEFjvtXw3k+ndOloIkwYMkpuAbO6nxmI1IyuUaqb2oz/yKRVRugSVqBmGXdYBtjt8tjDuwkwcBkIgefBujYKRkxhk4hoidwKy8ofdkT5tMK0Fj4tvfe0GzCQdfN6fknoNAbELI3wUK+otUgVDoCK32ZQ+fBgtmvzMLMj8HMOU/lxJLh/Y2UffipoAG5MBrmU0OcvOFOkrhDlTAJOuseVtiVDIQglI433zp5GRrkFnF2TZDNTXsYju5KrqN4B+BrdaReOCsagde1C6bpFcIeSn5hVyXK+8eBXW9Ek919kL1TAPC9WPQ= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
